# URL
spring.datasource.url=jdbc:postgresql://db.ycvecpqbxmjjnpeoeixm.supabase.co:5432/postgres

# Usuário
spring.datasource.username=postgres

# Senha
spring.datasource.password=Edu_321-

# Spring Security
spring.security.user.name=admin
spring.security.user.password=$2a$10$78sh2F2VRCMQBv4KFS5q8.im86dx1/xadC5duRNa4jjLHAJf9Bfg6

spring.security.user.roles=ADMIN

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configs
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.application.name=redesocial

# Google GCP
spring.cloud.gcp.parametermanager.enabled=false
spring.cloud.gcp.storage.enabled=false

